#!/bin/env bash
#install ngnix and let it prints hello world

apt-get -y update
apt-get -y install ngnix
ufw allow 'Nginx HTTP'
echo "Hellow World!"> | sudo tee /var/www/html/index.html
services ngnix start 