#!/bin/env bash
#install ngnix and let it prints hello world

sudo apt-get -y update
sudo apt-get -y install ngnix
sudo ufw allow 'Nginx HTTP'
sudo echo "Hello World!" > /var/www/html/index.html
sudo service nginx start 
