#!/bin/env bash
#install ngnix and let it prints hello world

sudo apt-get -y update
sudo apt-get -y install ngnix
sudo ufw allow 'Nginx HTTP'
echo "Hellow World!"> | sudo tee /var/www/html/index.html
sudo services ngnix start 