#!/usr/bin/env bash
#install ngnix and let it prints hello world

sudo apt-get update
sudo apt-get install -y nginx
the_link="www.youtube.com/watch?v=QH2-TGUlwu4"

echo "Hello World!" | sudo tee /var/www/html/index.html
string_1="server_name _;\n\trewrite ^\/redirect_me https:\/\/$the_link permanent;"
sudo sed -i "s/server_name _;/$string_1/" /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
string_2="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_2/" /etc/nginx/sites-enabled/default

sudo service nginx restart
