#!/usr/bin/env bash
# Display time in minutes from hours 0 to 12
COUNTER=59
HOUR=0
while [ $HOUR -lt 14 ];do
	((COUNTER=COUNTER+1))
	if [ $COUNTER -ne 60 ]
	then
		echo "$COUNTER"
	else
		if [ $HOUR -ne 13 ]
		then
			echo "Hour: $HOUR"
		fi
		((COUNTER=0))
		((HOUR=HOUR+1))
	fi
done